sudo: false
language: node_js
node_js:
  - "5"
before_script:
  - npm install -g gulp
script:
  - gulp build
  - gulp coverage
  - node webtest/test.js
cache:
  directories:
    - "node_modules"
addons:
  sauce_connect:
    username: "ender336"
    access_key: "fcfad206-6db2-46bc-8824-c1e576d549cf"